### ISSUE TITLE
Requires Python 3.7 on Windows

### ISSUE THREAD

**Issue by baoilleach** [sixty-north/cosmic-ray#454]
I can't see this in the documentation, but I note that the pip installed version (installed today) does not work with Python 3.6 (x64) on Windows. All tests fail as 'incompetent'. When I look at the HTML report, they all have:
```
Traceback (most recent call last):
  File "c:\tools\partialsmiles\partialsmiles\env\lib\site-packages\cosmic_ray\worker.py", line 66, in worker
    test_outcome, output = run_tests(test_command, timeout)
  File "c:\tools\partialsmiles\partialsmiles\env\lib\site-packages\cosmic_ray\testing.py", line 75, in run_tests
    asyncio.WindowsProactorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsProactorEventLoopPolicy'
``` 
This particular method was introduced in Python 3.7. See end of https://docs.python.org/3/whatsnew/3.7.html#asyncio

Let me know if you need any further details.

**Comment by abingham** [comment]
Thanks for reporting this. We probably just need to make 3.7 our required version for Windows...I'm not sure how easily I can do without the proactor.
